# Generated by Django 6.1 on 2026-08-19 23:44

import chalk.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled board', max_length=200)),
                ('surface', models.CharField(choices=[('black', 'Blackboard'), ('green', 'Green chalkboard'), ('white', 'Whiteboard'), ('grid', 'Grid paper'), ('ruled', 'Ruled paper')], default='black', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chalk_boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BoardSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('token', models.CharField(default=chalk.models.make_token, max_length=64)),
                ('page_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='chalk.board')),
            ],
        ),
        migrations.CreateModel(
            name='BoardPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.PositiveIntegerField(default=0)),
                ('strokes', models.JSONField(blank=True, default=list)),
                ('history', models.JSONField(blank=True, default=list)),
                ('undone', models.JSONField(blank=True, default=list)),
                ('els', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='chalk.board')),
            ],
            options={
                'ordering': ['index'],
                'constraints': [models.UniqueConstraint(fields=('board', 'index'), name='chalk_page_unique_index')],
            },
        ),
    ]
