# Generated by Django 5.0.6 on 2026-05-10 22:15

import django.db.models.deletion
import presentations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default=presentations.models._gen_code, max_length=6, unique=True)),
                ('kind', models.CharField(choices=[('poll', 'Poll'), ('game', 'Game')], max_length=10)),
                ('state', models.CharField(choices=[('lobby', 'Lobby'), ('running', 'Running'), ('ended', 'Ended')], default='lobby', max_length=10)),
                ('mode', models.CharField(choices=[('orchestra', 'Orchestra'), ('open', 'Open')], default='orchestra', max_length=20)),
                ('current_question_index', models.IntegerField(default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
                ('questionnaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.questionnaire')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_uid', models.CharField(db_index=True, max_length=64)),
                ('nickname', models.CharField(max_length=40)),
                ('avatar_id', models.CharField(default='dragon', max_length=30)),
                ('room_id', models.CharField(blank=True, max_length=40)),
                ('score', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='presentations.livesession')),
            ],
            options={
                'ordering': ['-score', 'joined_at'],
                'unique_together': {('session', 'participant_uid')},
            },
        ),
    ]
