"""Word, Excel, PDF and standalone HTML exports for Kura cleaned datasets."""

from __future__ import annotations

import html
import io
import json
from datetime import datetime

from django.http import HttpResponse

from .analytics import dashboard_payload, run_dataframe


def _filename(run, ext):
    code = run.pipeline.survey.code
    return f"{code}_cleaning_run_{run.id}.{ext}"


def export_excel(run):
    import pandas as pd

    df = run_dataframe(run)
    changes = list(run.changes.values(
        "row_number", "field", "change_type", "old_value", "new_value", "detail"
    ))
    steps = list(run.pipeline.steps.values(
        "order", "name", "operation", "enabled", "config", "note"
    ))
    stats = dashboard_payload(run)

    out = io.BytesIO()
    with pd.ExcelWriter(out, engine="openpyxl") as writer:
        df.to_excel(writer, sheet_name="Cleaned Data", index=False)
        pd.DataFrame(changes).to_excel(writer, sheet_name="Change Log", index=False)
        pd.DataFrame(steps).to_excel(writer, sheet_name="Pipeline Steps", index=False)
        pd.DataFrame(stats.get("numeric", {})).T.to_excel(writer, sheet_name="Summary Statistics")
        corr = stats.get("correlation", {})
        if corr.get("columns"):
            pd.DataFrame(
                corr["matrix"], index=corr["columns"], columns=corr["columns"]
            ).to_excel(writer, sheet_name="Correlation Matrix")
    response = HttpResponse(
        out.getvalue(),
        content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    )
    response["Content-Disposition"] = f'attachment; filename="{_filename(run, "xlsx")}"'
    return response


def _report_context(run):
    return {
        "survey": run.pipeline.survey,
        "run": run,
        "stats": dashboard_payload(run),
        "rows": list(run.records.order_by("row_number")[:100]),
        "changes": list(run.changes.select_related("step").order_by("id")[:500]),
    }


def export_html(run):
    ctx = _report_context(run)
    stats = ctx["stats"]
    numeric_rows = "".join(
        f"<tr><td>{html.escape(name)}</td><td>{v.get('count')}</td>"
        f"<td>{v.get('mean')}</td><td>{v.get('median')}</td>"
        f"<td>{v.get('min')}</td><td>{v.get('max')}</td></tr>"
        for name, v in stats.get("numeric", {}).items()
    )
    doc = f"""<!doctype html>
<html><head><meta charset="utf-8"><title>{html.escape(ctx['survey'].title)} report</title>
<style>
body{{font:15px Arial,sans-serif;color:#202124;max-width:1100px;margin:40px auto;padding:0 25px}}
h1,h2{{color:#30205f}} .meta{{background:#f3f0ff;padding:16px;border-radius:10px}}
table{{border-collapse:collapse;width:100%;margin:15px 0}}th,td{{border:1px solid #ddd;padding:8px;text-align:left}}
th{{background:#30205f;color:white}} .small{{font-size:12px;color:#666}}
</style></head><body>
<h1>{html.escape(ctx['survey'].title)}</h1>
<div class="meta"><b>Cleaning report</b><br>
Pipeline: {html.escape(run.pipeline.name)}<br>
Run: {run.id} · Rows: {run.result_count} · Changes: {run.changes.count()}<br>
Generated: {datetime.utcnow().isoformat()} UTC</div>
<h2>Executive summary</h2>
<p>The cleaned result contains {run.result_count} rows and {run.column_count} columns.
The pipeline removed {run.excluded_count} rows and recorded {run.changes.count()} auditable changes.</p>
<h2>Pipeline steps</h2>
<ol>{''.join(f"<li><b>{html.escape(s.name)}</b> — {html.escape(s.operation)}</li>" for s in run.pipeline.steps.order_by("order"))}</ol>
<h2>Numeric summary</h2>
<table><thead><tr><th>Variable</th><th>N</th><th>Mean</th><th>Median</th><th>Min</th><th>Max</th></tr></thead>
<tbody>{numeric_rows}</tbody></table>
<h2>Correlation matrix</h2>
<pre>{html.escape(json.dumps(stats.get("correlation", {}), indent=2))}</pre>
<p class="small">Generated by Kura Data Studio.</p>
</body></html>"""
    response = HttpResponse(doc, content_type="text/html; charset=utf-8")
    response["Content-Disposition"] = f'attachment; filename="{_filename(run, "html")}"'
    return response


def export_word(run):
    try:
        from docx import Document
        from docx.shared import Inches
    except ImportError as exc:
        raise RuntimeError("python-docx is required for Word export.") from exc

    ctx = _report_context(run)
    stats = ctx["stats"]
    doc = Document()
    doc.add_heading(ctx["survey"].title, 0)
    doc.add_paragraph(
        f"Cleaning report · Pipeline: {run.pipeline.name} · Run #{run.id}"
    )
    doc.add_heading("Executive summary", level=1)
    doc.add_paragraph(
        f"The cleaned result contains {run.result_count} rows and "
        f"{run.column_count} columns. {run.excluded_count} rows were removed "
        f"and {run.changes.count()} changes were recorded."
    )
    doc.add_heading("Pipeline steps", level=1)
    for step in run.pipeline.steps.order_by("order"):
        doc.add_paragraph(
            f"{step.order}. {step.name} ({step.operation})",
            style="List Number",
        )
    doc.add_heading("Numeric summary", level=1)
    table = doc.add_table(rows=1, cols=6)
    hdr = table.rows[0].cells
    for i, label in enumerate(["Variable", "N", "Mean", "Median", "Min", "Max"]):
        hdr[i].text = label
    for name, values in stats.get("numeric", {}).items():
        cells = table.add_row().cells
        data = [
            name, values.get("count"), values.get("mean"),
            values.get("median"), values.get("min"), values.get("max"),
        ]
        for i, value in enumerate(data):
            cells[i].text = "" if value is None else str(value)
    out = io.BytesIO()
    doc.save(out)
    response = HttpResponse(
        out.getvalue(),
        content_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    )
    response["Content-Disposition"] = f'attachment; filename="{_filename(run, "docx")}"'
    return response


def export_pdf(run):
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4, landscape
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.lib.units import mm
        from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
    except ImportError as exc:
        raise RuntimeError("reportlab is required for PDF export.") from exc

    ctx = _report_context(run)
    stats = ctx["stats"]
    out = io.BytesIO()
    doc = SimpleDocTemplate(
        out, pagesize=A4, rightMargin=16*mm, leftMargin=16*mm,
        topMargin=16*mm, bottomMargin=16*mm,
    )
    styles = getSampleStyleSheet()
    story = [
        Paragraph(ctx["survey"].title, styles["Title"]),
        Paragraph(f"Cleaning report · Pipeline {run.pipeline.name} · Run #{run.id}", styles["Normal"]),
        Spacer(1, 10),
        Paragraph("Executive summary", styles["Heading1"]),
        Paragraph(
            f"The cleaned result contains {run.result_count} rows and {run.column_count} columns. "
            f"{run.excluded_count} rows were removed and {run.changes.count()} changes were recorded.",
            styles["BodyText"],
        ),
        Paragraph("Numeric summary", styles["Heading1"]),
    ]
    table_data = [["Variable", "N", "Mean", "Median", "Min", "Max"]]
    for name, v in stats.get("numeric", {}).items():
        table_data.append([
            name, v.get("count"), v.get("mean"), v.get("median"), v.get("min"), v.get("max")
        ])
    table = Table(table_data, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#30205f")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), .5, colors.grey),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    story.append(table)
    doc.build(story)
    response = HttpResponse(out.getvalue(), content_type="application/pdf")
    response["Content-Disposition"] = f'attachment; filename="{_filename(run, "pdf")}"'
    return response
