# Generated by Django 6.1 on 2026-08-31 09:04

import django.db.models.deletion
import django.utils.timezone
import publish.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=70, unique=True)),
                ('uses', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('article', 'Article'), ('dataset', 'Dataset'), ('deck', 'Slide deck'), ('board', 'Board'), ('card', 'Card'), ('show', 'Show')], default='article', max_length=16)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('abstract', models.TextField(blank=True, help_text='A short summary. Shown in the index and in link previews.')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='publications/covers/%Y/%m/')),
                ('cover_credit', models.CharField(blank=True, max_length=200)),
                ('source_app', models.CharField(blank=True, max_length=40)),
                ('source_ref', models.CharField(blank=True, max_length=64)),
                ('source_label', models.CharField(blank=True, help_text='Name of the source at publish time.', max_length=220)),
                ('source_variant', models.CharField(blank=True, help_text='e.g. clean / raw for a dataset.', max_length=32)),
                ('license', models.CharField(choices=[('cc-by-4.0', 'Creative Commons Attribution 4.0'), ('cc-by-sa-4.0', 'Creative Commons Attribution-ShareAlike 4.0'), ('cc-by-nc-4.0', 'Creative Commons Attribution-NonCommercial 4.0'), ('cc0-1.0', 'Public domain dedication (CC0 1.0)'), ('odbl-1.0', 'Open Database Licence 1.0'), ('arr', 'All rights reserved')], default='cc-by-4.0', max_length=24)),
                ('language', models.CharField(default='en', max_length=12)),
                ('funding', models.CharField(blank=True, max_length=300)),
                ('collected_between', models.CharField(blank=True, help_text='Free text period, e.g. Mar–Jun 2026.', max_length=120)),
                ('coverage_area', models.CharField(blank=True, help_text='Where the work covers.', max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('changes', 'Changes requested'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], default='public', max_length=12)),
                ('allow_embed', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('citation_key', models.CharField(blank=True, max_length=24, unique=True)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('featured_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('first_published_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading_seconds', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='publications/og/%Y/%m/')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications_reviewed', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='publications', to='publish.tag')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicationAuthor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('affiliation', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('orcid', models.CharField(blank=True, max_length=40)),
                ('role', models.CharField(blank=True, help_text='e.g. Field coordinator, Analyst.', max_length=80)),
                ('is_corresponding', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='publish.publication')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_publications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PublicationBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('heading', 'Heading'), ('text', 'Paragraph'), ('figure', 'Figure'), ('quote', 'Quote'), ('list', 'List'), ('code', 'Code'), ('table', 'Table'), ('embed', 'Embed'), ('callout', 'Callout'), ('divider', 'Divider')], default='text', max_length=16)),
                ('text', models.TextField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=400)),
                ('image', models.ImageField(blank=True, null=True, upload_to='publications/figures/%Y/%m/')),
                ('url', models.URLField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('anchor', models.SlugField(blank=True, max_length=80)),
                ('figure_number', models.PositiveIntegerField(blank=True, null=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='publish.publication')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReviewNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('changes', 'Changes requested'), ('comment', 'Comment'), ('unpublished', 'Unpublished')], default='comment', max_length=16)),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_notes', to='publish.publication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('link', 'Copied link'), ('embed', 'Copied embed'), ('qr', 'QR code'), ('x', 'X'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('email', 'Email'), ('native', 'Device share sheet')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_events', to='publish.publication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetricDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.DateField(db_index=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_days', to='publish.publication')),
            ],
            options={
                'ordering': ['-day'],
                'unique_together': {('publication', 'day')},
            },
        ),
        migrations.CreateModel(
            name='PublicationAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('role', models.CharField(choices=[('primary', 'Primary file'), ('data', 'Data file'), ('codebook', 'Codebook'), ('preview', 'Preview'), ('thumbnail', 'Thumbnail'), ('extra', 'Supplementary')], default='extra', max_length=16)),
                ('label', models.CharField(max_length=160)),
                ('file', models.FileField(upload_to=publish.models.asset_path)),
                ('media_type', models.CharField(blank=True, max_length=100)),
                ('extension', models.CharField(blank=True, max_length=12)),
                ('byte_size', models.PositiveBigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, help_text='sha256 of the frozen file.', max_length=64)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('column_count', models.PositiveIntegerField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='publish.publication')),
            ],
            options={
                'ordering': ['order', 'role', 'label'],
                'indexes': [models.Index(fields=['publication', 'version'], name='publish_pub_publica_d775ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='PublicationVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(default=1)),
                ('changelog', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='publish.publication')),
            ],
            options={
                'ordering': ['-number'],
                'unique_together': {('publication', 'number')},
            },
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['kind', 'status'], name='publish_pub_kind_08e294_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['status', '-published_at'], name='publish_pub_status_d4efd0_idx'),
        ),
    ]
