# Generated by Django 5.0.6 on 2026-05-10 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0001_initial'),
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_responses', to='presentations.livesession'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['question', 'session'], name='polls_respo_questio_90ad47_idx'),
        ),
    ]
