# Generated by ChatGPT for KnockKnock Quest RPG
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import quest_rpg.models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name='QuestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('title', models.CharField(default='Untitled Quest', max_length=160)),
                ('world', models.CharField(choices=[('jungle', 'Jungle Treasure'), ('sea', 'Deep Sea Quest'), ('space', 'Space Mission'), ('cave', 'Crystal Cave'), ('forest', 'Mystic Forest')], default='jungle', max_length=20)),
                ('team_size', models.PositiveIntegerField(default=4, help_text='Recommended team size. Use 0 for unlimited/N.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('live', 'Live'), ('ended', 'Ended')], default='draft', max_length=10)),
                ('current_question', models.PositiveIntegerField(default=0)),
                ('allow_rejoin', models.BooleanField(default=True)),
                ('show_correct_after_answer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_rpg_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-updated_at']},
        ),
        migrations.CreateModel(
            name='QuestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('prompt', models.TextField()),
                ('option_a', models.CharField(blank=True, max_length=500)),
                ('option_b', models.CharField(blank=True, max_length=500)),
                ('option_c', models.CharField(blank=True, max_length=500)),
                ('option_d', models.CharField(blank=True, max_length=500)),
                ('correct_option', models.CharField(default='A', max_length=1)),
                ('points', models.PositiveIntegerField(default=100)),
                ('treasure_hint', models.CharField(blank=True, max_length=240)),
                ('danger_text', models.CharField(blank=True, max_length=240)),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quest_rpg.questsession')),
            ],
            options={'ordering': ['position', 'id']},
        ),
        migrations.CreateModel(
            name='QuestTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('avatar', models.CharField(choices=[('explorer', 'Explorer'), ('warrior', 'Warrior'), ('wizard', 'Wizard'), ('robot', 'Robot'), ('astronaut', 'Astronaut'), ('pirate', 'Pirate'), ('mermaid', 'Mermaid'), ('dragon', 'Dragon'), ('lion', 'Lion'), ('eagle', 'Eagle')], default='explorer', max_length=30)),
                ('points', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='quest_rpg.questsession')),
            ],
            options={'ordering': ['-points', '-correct_count', 'created_at'], 'unique_together': {('session', 'name')}},
        ),
        migrations.CreateModel(
            name='QuestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quest_rpg.questquestion')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quest_rpg.questteam')),
            ],
            options={'ordering': ['answered_at'], 'unique_together': {('team', 'question')}},
        ),
    ]
