# Generated by Django 6.0.7 on 2026-07-11 21:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('duplicate', 'Duplicate responses'), ('outlier', 'Numeric outliers'), ('speeder', 'Too-fast completions'), ('straightliner', 'Straight-lining'), ('geofence', 'GPS outside area'), ('missing', 'Missing critical answers'), ('logic', 'Custom logic check'), ('recode', 'Recode values')], max_length=16)),
                ('action', models.CharField(choices=[('flag', 'Flag'), ('exclude', 'Exclude'), ('recode', 'Recode')], default='flag', max_length=8)),
                ('config', models.JSONField(default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Phone', max_length=80)),
                ('platform', models.CharField(blank=True, max_length=40)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kura_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('schema', models.JSONField(default=dict)),
                ('schema_hash', models.CharField(blank=True, max_length=64)),
                ('is_current', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kura_published_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('answers', models.JSONField(default=dict)),
                ('calculations', models.JSONField(default=dict)),
                ('score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('partial', 'Partial'), ('flagged', 'Flagged'), ('excluded', 'Excluded')], default='complete', max_length=10)),
                ('source', models.CharField(choices=[('web', 'Web runner'), ('api', 'Mobile app (sync)')], default='web', max_length=6)),
                ('gps_lat', models.FloatField(blank=True, null=True)),
                ('gps_lng', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='kura.device')),
                ('enumerator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kura_submissions', to=settings.AUTH_USER_MODEL)),
                ('form_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='kura.formversion')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='AnswerEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=80)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('rule_name', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kura_edits', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='kura.submission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(blank=True, max_length=80)),
                ('detail', models.CharField(blank=True, max_length=240)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='kura.cleaningrule')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='kura.submission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('title', models.CharField(default='Untitled survey', max_length=140)),
                ('description', models.TextField(blank=True, default='')),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('collecting', 'Collecting'), ('paused', 'Paused'), ('closed', 'Closed')], default='draft', max_length=12)),
                ('draft_schema', models.JSONField(default=dict)),
                ('quota', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kura_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='kura.survey'),
        ),
        migrations.AddField(
            model_name='formversion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='kura.survey'),
        ),
        migrations.AddField(
            model_name='cleaningrule',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_rules', to='kura.survey'),
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pushed', models.PositiveIntegerField(default=0)),
                ('duplicates', models.PositiveIntegerField(default=0)),
                ('rejected', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='kura.device')),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kura.survey')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['survey', 'status'], name='kura_submis_survey__6c0719_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['survey', 'received_at'], name='kura_submis_survey__ac2c70_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='formversion',
            unique_together={('survey', 'version')},
        ),
    ]
