# Generated by Django 5.0.6 on 2026-05-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(max_length=64)),
                ('nickname', models.CharField(max_length=40)),
                ('avatar_id', models.CharField(default='dragon', max_length=30)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_taken_ms', models.PositiveIntegerField(default=0)),
                ('points_awarded', models.IntegerField(default=0)),
                ('room_id', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GameQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='game_question_images/')),
                ('time_limit', models.PositiveIntegerField(default=20, help_text='Seconds to answer')),
                ('points', models.PositiveIntegerField(default=1000)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('template_id', models.CharField(default='neon', max_length=40)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='quiz_logos/')),
                ('scoring', models.CharField(choices=[('speed', 'Speed — first correct gets the points'), ('accuracy', 'Accuracy — number of correct answers wins')], default='speed', max_length=20)),
                ('mode', models.CharField(choices=[('orchestra', 'Orchestra (presenter-controlled)'), ('open', 'Open (self-paced)')], default='orchestra', max_length=20)),
                ('use_rooms', models.BooleanField(default=False, help_text='If true, participants are split into capped rooms.')),
                ('room_capacity', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
