# Generated by Django 5.0.6 on 2026-05-10 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('presentations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gameanswer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_answers', to='presentations.livesession'),
        ),
        migrations.AddField(
            model_name='gameanswer',
            name='choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.gamechoice'),
        ),
        migrations.AddField(
            model_name='gamechoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='games.gamequestion'),
        ),
        migrations.AddField(
            model_name='gameanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gamequestion'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='games.quiz'),
        ),
        migrations.AddIndex(
            model_name='gameanswer',
            index=models.Index(fields=['session', 'participant_id'], name='games_gamea_session_32e38f_idx'),
        ),
    ]
